### ISSUE TITLE
Code and parameterization issues

### ISSUE THREAD

**Issue by z704898182** [JonZwe/PFAScreen#1]
Should "xraxis" be changed to "xaxis" in line 287 of the plotting.py file. 
I got an error during the "Save HTML MSMS spectra?" process, but after modifying it, the problem was solved.

In addition, I would like to ask whether the "Noise threshold" seted for MS and MS/MS in the software is the same for Orbitrap and QToF instruments, and whether there is a recommended range of values.

Your team has developed a very creative software and I hope I can use it in my research!

**Comment by JonZwe** [comment]
Thank you for pointing to that error! 
I corrected it in the main branch!
So the threshold generally very much depends on the used instrument. To my knowledge in Orbitrap instruments, the arbitrary intensity units are usually higher than for TOF instruments. We recommend starting with a higher threshold for both MS and MS2, look at the outcomes (e.g., number of detected features) and adjust it according to your knowledge! For TOF data we are usually in the range of 500 to 1000 as threshold which might be too low for Orbitraps!

**Comment by z704898182** [comment]
Thanks for your reply, I will set some values to find the right threshold.
