### ISSUE TITLE
Difficulties during Feature finding

### ISSUE THREAD

**Issue by MichaelMohr01** [JonZwe/PFAScreen#4]
Hi,
I'm having some difficulties with the feature finding (on Windows 11 and Python 3.11).
When I try it with my mzML converted file (I've tried peak picking and a collision energy subset, since the data was recorded using a CE spread on a ScieX QTOF, with the same result.) I recieve the following error message:
C:\Users\micha\Arbeit\Langenau\PFAScreen-main>python3 run_PFAScreen.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\micha\Arbeit\Langenau\PFAScreen-main\run_PFAScreen.py", line 45, in RunFeatureFinding
    Df_FeatureData, Df_MS2RawData, idx_in_features, exps = feature_preproccessing(
                                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\Arbeit\Langenau\PFAScreen-main\feature_preproccessing.py", line 62, in feature_preproccessing
    exp, feature_map = MS1_feature_finding(sample,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\Arbeit\Langenau\PFAScreen-main\MS1_feature_finding.py", line 13, in MS1_feature_finding
    MzMLFile().load(sample, exp)
  File "pyopenms\\_pyopenms_5.pyx", line 12896, in pyopenms._pyopenms_5.MzMLFile.load
**RuntimeError: - due to that error of type InvalidValue in: D:\a\OpenMS\OpenMS\OpenMS\src\openms\source\METADATA\Precursor.cpp@151-void __cdecl OpenMS::Precursor::setIsolationWindowUpperOffset(double)**

Is there a problem with my mzML files or do you have any idea what causes this error?
Thank you for your time.
Best regards

**Comment by JonZwe** [comment]
Hi,
thanks for reporting this issue! Yes, it seems that the error arises from the mzML file itself. It happens at the position where the file usually should be loaded, so even before feature detection. Have you checked the size of the mzML file (should be in the order of 100 MB)? Sometimes they are empty which could cause this error. If you want to, you could also try sending me the file. However, if the mzML file itself is damaged than the error occurs during conversion with MSConvert. Maybe there is any information online on similar problems with Bruker files. Have you tried both centroiding algorithms, and also without CE filtering?
Best regards,
Jonathan

**Comment by MichaelMohr01** [comment]
I've tried both centroiding algorithms and also without CE filtering with the same result. I assume the problem is caused by my ScieX ddA method, since it uses a CE as well as a CE spread. I've included one of my mzML files, which are around 25MB (cwt peak picking, no CE filtering). I'm going to measure again tommorow using a fixed CE and hope to solve the issue that way. 
Best regards
Michael 
[23-10-19_NTS_18_Rastatt_soilB1_Aq10_4035_Inj1.zip](https://github.com/JonZwe/PFAScreen/files/13636606/23-10-19_NTS_18_Rastatt_soilB1_Aq10_4035_Inj1.zip)

**Comment by MichaelMohr01** [comment]
So I've tried measuring again using a fixed collision energy but with no success. I also tried a file of a colleague, who is using an Orbitrap and it worked fine, so i assume the problem is somehow caused by mzML files originating from ScieX instruments.

**Comment by JonZwe** [comment]
Hi Michael,
I googled this issue, and it indeed seems to be a common problem with the data conversion from ScieX files! Whenever I can figure out how it can be performed without errors I will let you know! It would be a pity if its not possible!

**Comment by MichaelMohr01** [comment]
Thank you for your effort. I just found out, that the older .wiff file format works fine but the newer .wiff2 doesn't. When I compared the files, I found out, that MSConvert uses the .wiff and a .wiff.scan file to create the .mzML file for the old data format but only the .wiff2 file in the new data format. Even though a .wiff.scan file was available in the same folder.  I've added both .mzML files, so you can have a look. Do you think this could cause the problem and if so, do you know if I can force MSConvert to use the .wiff.scan file as well?
Happy holidays and kind regards.
[wiff_wiff2.zip](https://github.com/JonZwe/PFAScreen/files/13761449/wiff_wiff2.zip)

**Comment by JonZwe** [comment]
Hi Michael,
I have to admit that I don't have experience with ScieX files. I tested your files and the "wiff_23-10-10_Zor04_n_15_155448-04_KW39_Di_Donau_23-09-26_Inj1" seems to work fine, however, in case of "wiff2_23-10-19_NTS_12_STD_500" the same error during data reading occurs. Maybe you could directly contact the developers of MSConvert or search for papers that previously converted ScieX files?  
I also noticed that almost no features were detected in the file that works, and only with a rather low threshold some features could be detected but seemed to be of rather bad quality. Do you expect this sample to contain many compounds, or is it just a rather clean water sample?
Best,
Jonathan

**Comment by MichaelMohr01** [comment]
The file that works is either a blank or water, I didn't expect any peakts I just used the file for testing pruposes. At the moment I'm trying to get it to work but I'm somewhat time limited and  I might just end up measuring using an Orbitrap.

**Comment by JonZwe** [comment]
Could you send me the newer ScieX files? Then I can also try it myself?

**Comment by MichaelMohr01** [comment]
Of course I can also upload some unconverted ScieX files. This measurement is of a PFAS standard containing carboxylic and sulfonic acids as well as FOSA and 6:2 FTS  at 1000 ng/L as well as internal standards. If you need more information or additional files please feel free to contact me.
[n.zip](https://github.com/JonZwe/PFAScreen/files/13871554/n.zip)

**Comment by JonZwe** [comment]
Hi,
this file worked out for me! 
This is how I converted it:
![image](https://github.com/JonZwe/PFAScreen/assets/97395596/9446ce03-b588-4b5a-9145-0045b7ba1c21)
Could it be that you have not dragged the peak picking as the first processing step?
And I used an intensity threshold of 200, no isotope model, and a KMD mass tolerance of 0.005 Da.
This are the HS that were detected! For me it seems correct at the first glance!
![image](https://github.com/JonZwe/PFAScreen/assets/97395596/bcf984cc-ab4a-49d2-802e-faac266fdf57)
Is that what you would expect in the standard?

**Comment by MichaelMohr01** [comment]
It seems that i had deleted the titleMaker by accident. I just tried it and it doesn't seem to work without it for .wiff2 files.
Tried it with your settings and it's working fine. From the standard file I would expect a homologues series of perfluoro sulfonic- and one of carboxylic acids.
Thank you so much for your help, I'm sorry the problem was caused by such a mix up.

**Comment by JonZwe** [comment]
Perfect! Then I'm happy that it worked out!
Your are welcome!
